name: First Workflow

on: workflow_dispatch

jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: Say Goodbye
        run: echo "Goodbye!!"
  second-job:
    name: Second Job
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World 2!"
      - name: Say Goodbye
        run: echo "Goodbye 2!!"
